# Generated by Django 5.2.1 on 2025-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NebulaNotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomicalobject',
            name='discovery_date',
        ),
        migrations.AddField(
            model_name='astronomicalobject',
            name='discovery_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astronomicalobject',
            name='distance_from_earth',
            field=models.FloatField(help_text='in light years'),
        ),
    ]
