# Generated by Django 5.1.4 on 2025-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NebulaNotesApp', '0003_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='blabla',
        ),
    ]
