# Generated by Django 5.2.1 on 2025-05-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NebulaNotesApp', '0004_remove_observation_blabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='astronomical_object',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='NebulaNotesApp.astronomicalobject'),
            preserve_default=False,
        ),
    ]
