# Generated by Django 5.2.1 on 2025-05-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NebulaNotesApp', '0005_remove_objectobservation_astronomical_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectobservation',
            name='astronomical_object',
        ),
        migrations.RemoveField(
            model_name='objectobservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_objects',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='astronomicalobject',
            name='image',
        ),
        migrations.DeleteModel(
            name='EventObservation',
        ),
        migrations.DeleteModel(
            name='ObjectObservation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
