# Generated by Django 5.2.1 on 2025-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NebulaNotesApp', '0006_remove_objectobservation_astronomical_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomicalobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='astronomy_images/'),
        ),
    ]
